### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by RadW2020** [GeneticFractals/GeneticFractal2D-1#1]
Hi, 
I am trying to make this work but I have some issues with execution
I have renamed data-1.txt to data.txt, and I get this error

```
/usr/lib/ruby/2.3.0/tk/itemconfig.rb:115:in `hash_kv': wrong argument type nil (expected Array) (TypeError)
    from /usr/lib/ruby/2.3.0/tk/itemconfig.rb:115:in `itemconfig_hash_kv'
    from /usr/lib/ruby/2.3.0/tk/canvas.rb:722:in `_parse_create_args'
    from /usr/lib/ruby/2.3.0/tk/canvas.rb:735:in `create'
    from /usr/lib/ruby/2.3.0/tk/canvas.rb:758:in `create_self'
    from /usr/lib/ruby/2.3.0/tk/canvas.rb:751:in `initialize'
    from GeneticFractal2D-1.rb:71:in `new'
    from GeneticFractal2D-1.rb:71:in `plotPoint'
    from GeneticFractal2D-1.rb:92:in `evaluate'
    from GeneticFractal2D-1.rb:114:in `mainPlot'
    from GeneticFractal2D-1.rb:132:in `<main>'
```

Thanks

**Comment by GeneticFractals** [comment]
Hi RadW2020,

I can’t replicate the error, using the attached code from GIT and the output.

FYI, I’m using Ruby 2.1, that might make a difference.

The error you get is in the tk library and I’m only using the basic tk functions. Try to run a simple tk program like tk-test.rb attached to see if tk works.

Rgds

Henk

**Comment by RadW2020** [comment]
I finally solved it. 

for some reason TK was not available for my Ruby compilation, so I keep rebuilding again and again while trying different libraríes.

Thanks for help :)

**Comment by RadW2020** [comment]
Can I ask you what math base has those data.txt files?

**Comment by GeneticFractals** [comment]
Check out the series: https://geneticfractals.org/2d-genetic-fractals-makers-guide/

The data.txt is a tab separated export from excel col0=s, col1=dR, col2=dPhi+, col3=dPhi-

Rgds

Henk

**Comment by RadW2020** [comment]
Part 2 of the guide is not working properly

https://geneticfractals.org/2014/10/03/2d-genetic-fractals-makers-guide-part-2-plotting-fractals/

I look forward to keep reading your work ;)
